apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: veltrix-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations: []
    version: 1
    editable: false
