apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: veltrixdb
  namespace: veltrixdb
  labels:
    app.kubernetes.io/name: veltrixdb
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: veltrixdb
  namespaceSelector:
    matchNames:
      - veltrixdb
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
